### ISSUE TITLE
Thumbnails are not created following the image upload

### ISSUE THREAD

**Issue by ongunsaracbasi** [jefking/fl-image-resize#1]
I was able to successfully upload blob to images container followed by the creation of the thumbnails. However after I did 2 or 3; thumbnails stopped appearing while images container was filling with images. I did restart the function app on Azure portal, following which all outstanding thumbnails were created at once in batch.

Is this an expected behaviour? Do I need to trigger Function specifically from my App to have the thumbnail creation done immediately after?

Thanks in advance for the help

**Comment by jefking** [comment]
Hi @ongunsaracbasi, this sounds like an issue. The thumbnails should be generated very shortly after the original is uploaded to Azure Storage. The trigger is in the repo, so you can look there.
I have not been able to reproduce this, please let me know if you can...
